
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const Licensing = () => {
  return (
    <div className="container py-8">
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl">Licensing Policy</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-slate dark:prose-invert max-w-none">
          <p>Last updated: April 22, 2025</p>
          
          <h2>1. Introduction</h2>
          <p>
            This licensing policy outlines the terms and conditions for using BlogForge's services and content.
          </p>
          
          <h2>2. Software License</h2>
          <p>
            BlogForge grants you a limited, non-exclusive, non-transferable license to access and use our software
            and services in accordance with this Licensing Policy and our Terms of Service.
          </p>
          
          <h3>2.1 Free Plan License</h3>
          <p>
            If you are using our Free Plan, you may:
          </p>
          <ul>
            <li>Create and manage up to 5 blog posts</li>
            <li>Use our basic AI post generation features</li>
            <li>Access basic analytics</li>
          </ul>
          
          <h3>2.2 Pro Plan License</h3>
          <p>
            If you have purchased our Pro Plan, you may:
          </p>
          <ul>
            <li>Create and manage unlimited blog posts</li>
            <li>Use all AI features without restrictions</li>
            <li>Access all advanced features as described in our service offering</li>
            <li>Use the service on one domain or subdomain</li>
          </ul>
          
          <h2>3. Content Ownership</h2>
          <p>
            You retain ownership of all content you create using our services. By using our services to create content, 
            you grant us a limited license to store, display, and process your content as necessary to provide our services.
          </p>
          
          <h2>4. AI-Generated Content</h2>
          <p>
            Content generated by our AI tools is provided for your use subject to the following terms:
          </p>
          <ul>
            <li>You own the rights to AI-generated content created for you through our platform</li>
            <li>You are responsible for reviewing and editing AI-generated content for accuracy, appropriateness, and legality</li>
            <li>We make no warranty regarding the originality of AI-generated content</li>
          </ul>
          
          <h2>5. Prohibited Uses</h2>
          <p>
            You may not:
          </p>
          <ul>
            <li>Reverse engineer, decompile, or disassemble our software</li>
            <li>Rent, lease, loan, sell, sublicense, or transfer the software to any third party</li>
            <li>Remove or alter any copyright, trademark, or other proprietary notices</li>
            <li>Use our services to create content that violates any law or regulation</li>
            <li>Create multiple accounts to circumvent plan limitations</li>
          </ul>
          
          <h2>6. Termination</h2>
          <p>
            This license will automatically terminate if you fail to comply with the terms outlined in this policy.
            Upon termination, you must cease all use of our services and delete any downloaded materials.
          </p>
          
          <h2>7. Lifetime Access</h2>
          <p>
            Our "lifetime access" for Pro Plan refers to the lifetime of the product. While we intend to maintain the
            product indefinitely, we reserve the right to discontinue the product with reasonable notice to users.
          </p>
          
          <h2>8. Contact Us</h2>
          <p>
            If you have any questions about this Licensing Policy, please contact us at licensing@blogforge.com.
          </p>
        </CardContent>
      </Card>
    </div>
  );
};

export default Licensing;
