// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhesnrwdpfkhaxmnreyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZXNucndkcGZraGF4bW5yZXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NjI2NzksImV4cCI6MjA1NTQzODY3OX0.9mvcJ5P24OtUFKSEoCyls9RaR2e4zugD1b4zizIzMM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);